config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create,:destroy, :new]
  resources :bands
  resources :albums
  resources :track 
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Album

end

app/controllers/band_controller.rb
class BandController < ApplicationController
  def index
    bands = Band.all
    render :index
  end

  def new
    @band  = Band.new
    render :new
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      rander :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def update
  @band = Band.find(params[:id])
  if @band.update(band_params)
    redirect_to bands_url(@band)
  else
    flash.now[:errors] = @band.errors.full_messages
    render :edit
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_current_user!
  def index
    @bands = Band.all
    render :index
  end

  def new
    @band  = Band.new
    render :new
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def update
  @band = Band.find(params[:id])
  if @band.update(band_params)
    redirect_to bands_url(@band)
  else
    flash.now[:errors] = @band.errors.full_messages
    render :edit
  end
end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/helpers/band_helper.rb
module BandHelper
end

app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>
<form action="<%=action_url%>" method="POST">
  <input type="hidden" name="_method" value="<%=http_method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
  <p>
    <label for="band_name"> band name
      <input type="text" name="band[name]" id = "band_name" value="<%= band.name%>">
    </label>
  </p>
  <input type ="submit">
</form>

app/views/bands/edit.html.erb
<h1>edit <%=@band.name%></h1>
<%=render "form", band: @band%>

app/views/bands/index.html.erb
<h1>Band names</h1>

<ul>
 <%@bands.each do |band| %>
  <li><%=link_to band.name, band_url(band)%></li>
 <%end%>
 </ul>

<% link_to "create new band", new_band_url %>

app/views/bands/new.html.erb
<h1>new Band</h1>
<%=render "form", band: @band%>

app/views/bands/show.html.erb
<!-- Each of your Band/Album/Track show pages should have links for:

Editing
Destroying
Up one level (Track to Album, Album to Band, Band to bands index).
Down one level (Band to each Album, Album to each Track).
Also a link to build one more of each. -->
<h1><%=@band.name%></h1>

<h2>albums</h2>

<ul>
<%@band.albums.each do |album| %>
  <li><%link_to album.name, album_url(album)%></li>
<%end%>
</ul>

<h3>links!</h3>
<ul>
  <li><%=link_to "add a Album",new_album_url(@band) %></li>
  <li><%=link_to "Edit band", edit_band_url(@band) %></li>
  <li><%=link_to "delete band", band_url(@band), method: :delete %></li>
  <li><%=link_to "all bands", bands_url %></li>
</ul>